FROM python:3.10.14


RUN apt update 
RUN apt install stress-ng cpulimit -y
RUN pip install --upgrade pip

WORKDIR /app
COPY requirements.txt /app

RUN pip install -r requirements.txt

COPY . /app

EXPOSE 7000

ENTRYPOINT ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "7000"]
